apiVersion: v1
kind: Pod
metadata:
  name: spark-deployment
  namespace: default
spec:
  containers:
  - name: spark-example
    imagePullPolicy: Never
    volumeMounts:
    - name: device-plugin
      mountPath: /var/lib/kubelet/device-plugins
    - name: aesm
      mountPath: /var/run/aesmd
    securityContext:
      privileged: true
    env:
    - name: EXECUTOR_MEMORY
      value: "512m"
    - name: NETTY_THREAD
      value: "32"
    - name: SGX_MEM_SIZE
      value: "8GB"
    - name: SGX_THREAD
      value: "256"
    - name: SGX_HEAP
      value: "1GB"
    - name: SGX_KERNEL_HEAP
      value: "1GB"
    - name: AZDCAP_DEBUG_LOG_LEVEL
      value: "fatal"
    - name: FS_TYPE
      value: "hostfs"
  volumes:
  - name: device-plugin
    hostPath:
      path: /var/lib/kubelet/device-plugins
  - name: aesm
    hostPath:
      path: /var/run/aesmd
